name: tiktok_like
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.0.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_storage: ^13.0.1
  flutter:
    sdk: flutter
  get: ^4.7.2
  image_picker: ^1.2.0
  video_compress: ^3.1.4
  video_player: ^2.10.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
